name: Fynd CI

"on":
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore Fynd.Api.csproj

      - name: Build
        run: dotnet build Fynd.Api.csproj --no-restore --configuration Release

      - name: Test
        run: dotnet test Fynd.Api.csproj --no-build --configuration Release
